title: "Le Mango Tree"
permalink: pretty
description: "Le Mango Tree, un nouveau bar à jus de fruits débarque sur Hossegor pour la saison 2015"
baseurl: /lemangotree
url: "http://www.lemangotree.com"

# Build settings
markdown: kramdown
